system:
  dir: 
  filesize: 

elasticsearch:
  url: 
  port: 
  protocol: 
  index: 
  doctype: 
  bulklimit: 

grok:
  patterns:
    # For example
    access.log:
      - '%{COMMONAPACHELOG}%{SPACE}\"%{DATA:usertest}\"'

